# Generated by Django 4.1.7 on 2023-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
