# Generated by Django 4.1.7 on 2023-04-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_options_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome completo'),
        ),
    ]
