# Generated by Django 4.1.7 on 2023-05-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_contasreceber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contasreceber',
            options={'verbose_name': 'Contas a receber', 'verbose_name_plural': 'Contas a receber'},
        ),
    ]
