# Generated by Django 4.1.7 on 2023-05-31 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiado',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do pagamento'),
        ),
    ]
