# Generated by Django 4.1.7 on 2023-06-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_cliente_expiracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='expiracao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_temporario_expiracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Código Temporário'),
        ),
    ]
