# Generated by Django 4.1.7 on 2023-04-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_vendedor_options_alter_vendedor_comissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='comissao',
            field=models.FloatField(verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='vendedor',
            field=models.CharField(max_length=100, verbose_name='Vendedor(a)'),
        ),
    ]
