# Generated by Django 4.1.7 on 2023-03-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_categoria_imagemproduto_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da variação'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(verbose_name='Preço da variação'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(default=0, verbose_name='Preço promo da variação'),
        ),
    ]
