# Generated by Django 4.1.7 on 2023-03-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_variacao_nome_alter_variacao_preco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
