# Generated by Django 4.1.7 on 2023-03-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_eu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eu',
        ),
    ]
