# Generated by Django 4.1.7 on 2023-03-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_delete_eu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemproduto',
            old_name='imagem',
            new_name='imagemP',
        ),
    ]
