# Generated by Django 4.1.7 on 2023-03-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_rename_imagem_imagemproduto_imagemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemproduto',
            old_name='imagemP',
            new_name='imagem',
        ),
    ]
