# Generated by Django 4.1.7 on 2023-04-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_fornecedor_produto_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='cpf',
        ),
    ]
