# Generated by Django 4.1.7 on 2023-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_remove_fornecedor_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
