# Generated by Django 4.1.7 on 2023-05-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_fornecedor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do pagamento')),
                ('valor', models.FloatField(verbose_name='Valor da dívida')),
                ('pagamento', models.CharField(max_length=100, verbose_name='Tipo de pagamento')),
                ('fornecedor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='produto.fornecedor', verbose_name='Cliente')),
            ],
        ),
    ]
