# Generated by Django 4.1.7 on 2023-05-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_contaspagar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contaspagar',
            options={'verbose_name': 'Contas a pagar', 'verbose_name_plural': 'Contas a pagar'},
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='produto.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
