# Generated by Django 4.1.7 on 2023-06-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_alter_contaspagar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='status',
            field=models.CharField(choices=[('D', 'Devendo'), ('P', 'Pago')], default='D', max_length=1),
        ),
    ]
