# Generated by Django 4.1.7 on 2023-06-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_contaspagar_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='variacao',
            name='cores',
            field=models.ManyToManyField(to='produto.cor', verbose_name='Cores da variação'),
        ),
    ]
