# Generated by Django 4.1.7 on 2023-06-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_remove_variacao_cores_delete_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='modalidade',
            field=models.CharField(choices=[('A', 'Atacado'), ('V', 'Varejo')], default='A', max_length=1),
        ),
    ]
