# Generated by Django 4.1.7 on 2023-06-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0018_influenciadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influenciadores',
            options={'verbose_name_plural': 'Influenciadores'},
        ),
    ]
