# Generated by Django 4.1.7 on 2023-06-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0020_influenciadores_variacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influenciadores',
            name='variacao',
        ),
    ]
