# Generated by Django 4.1.7 on 2023-06-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0021_remove_influenciadores_variacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='variacao',
            name='cores',
            field=models.ManyToManyField(blank=True, to='produto.cor'),
        ),
    ]
