# Generated by Django 4.1.7 on 2023-06-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0022_cor_variacao_cores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='cores',
        ),
        migrations.AddField(
            model_name='produto',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Cor',
        ),
    ]
