# Generated by Django 4.1.7 on 2023-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0023_remove_variacao_cores_produto_is_primary_delete_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Mostrar no template?'),
        ),
    ]
