# Generated by Django 4.1.7 on 2023-06-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0024_produto_cor_alter_produto_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/images/produto_imagens/%Y/%m/'),
        ),
    ]
