# Generated by Django 4.1.7 on 2023-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_caixa_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaAberto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65, verbose_name='Apelido do Caixa')),
                ('valor', models.FloatField(verbose_name='Valor de Abertura')),
            ],
        ),
        migrations.DeleteModel(
            name='Caixa',
        ),
    ]
