# Generated by Django 4.1.7 on 2023-05-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_caixaaberto_delete_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaaberto',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='C', max_length=1),
        ),
    ]
