# Generated by Django 4.1.7 on 2023-05-29 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_caixaaberto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaaberto',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Abertura'),
        ),
    ]
