# Generated by Django 4.1.7 on 2023-05-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_alter_caixaaberto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixaaberto',
            name='devolucao',
        ),
    ]
