# Generated by Django 4.1.7 on 2023-05-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_remove_caixaaberto_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaaberto',
            name='reforço',
            field=models.FloatField(default=1, verbose_name='Valor da Retirada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caixaaberto',
            name='retirada',
            field=models.FloatField(default=1, verbose_name='Valor do Reforço'),
            preserve_default=False,
        ),
    ]
