# Generated by Django 4.1.7 on 2023-05-31 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_caixaaberto_reforço_caixaaberto_retirada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reforço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reforço', models.FloatField(verbose_name='Valor do Reforço')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do reforço')),
            ],
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirada', models.FloatField(verbose_name='Valor da Retirada')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da retirada')),
            ],
        ),
        migrations.RemoveField(
            model_name='caixaaberto',
            name='reforço',
        ),
        migrations.RemoveField(
            model_name='caixaaberto',
            name='retirada',
        ),
    ]
