# Generated by Django 4.1.7 on 2023-05-29 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_devolucao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do pedido'),
        ),
    ]
