# Generated by Django 4.1.7 on 2023-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('C', 'Cartão'), ('D', 'Dinheiro')], default='C', max_length=1),
        ),
    ]
