# Generated by Django 4.1.7 on 2023-05-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_pedido_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('E', 'Enviado'), ('F', 'Finalizado')], default='L', max_length=1),
        ),
    ]
