# Generated by Django 4.1.7 on 2023-05-31 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_alter_contaspagar_options_and_more'),
        ('pedido', '0008_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='produto_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
            preserve_default=False,
        ),
    ]
