# Generated by Django 4.1.7 on 2023-05-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_itempedido_produto_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='produto_item',
        ),
    ]
