# Generated by Django 4.1.7 on 2023-06-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_cupom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupom',
            old_name='nome',
            new_name='codigo',
        ),
    ]
