# Generated by Django 4.1.7 on 2023-06-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0014_rename_nome_cupom_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupom',
            options={'verbose_name_plural': 'Cupons'},
        ),
    ]
