# Generated by Django 4.1.7 on 2023-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0015_alter_cupom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupom',
            options={},
        ),
        migrations.AlterField(
            model_name='cupom',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='valor',
            field=models.FloatField(),
        ),
    ]
